# FROM python:3.10-bullseye
# RUN python -m pip install --upgrade pip
# WORKDIR /app

# COPY poll/requirements.txt requirements.txt
# COPY poll/poller.py poller.py
# COPY manage.py manage.py
# COPY events_app events_app
# COPY events_project events_project
# COPY common common

# RUN pip install -r requirements.txt
# CMD python manage.py migrate && python poller.py
