volumes:
    mongo-data:
        external: true

services:
<<<<<<< HEAD
  sample_fastapi:
    build:
      context: sample_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./sample_service:/app

  # user_fastapi:
  #   build:
  #     context: user_service
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 8001:8000
  #     # look up iner vs outer
  #   volumes:
  #     - ./user_service:/app

  post_fastapi:
=======
  user:
>>>>>>> 6b804a6c79176277d8bced5ffa6da72520188075
    build:
      context: post_service
      dockerfile: Dockerfile.dev
    ports:
<<<<<<< HEAD
      - 8002:8000
      # look up iner vs outer
    volumes:
      - ./post_service:/app
=======
      - 8000:8000
    volumes:
      - ./user_service:/app
    environment:
      DATABASE_URL: mongodb://user:userpw@mongo
      DATABASE_NAME: userdb
      WAIT_HOSTS: mongo:27017
>>>>>>> 6b804a6c79176277d8bced5ffa6da72520188075
  
  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_API_HOST: http://localhost:8000
  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
      # - ./data:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: userpw
    # ports:
    #   - "27017:27017"
  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: userpw
      ME_CONFIG_MONGODB_URL: mongodb://user:userpw@mongo:27017/

