volumes:
    postgres-data:
        external: true

services:
  sample_fastapi:
    build:
      context: sample_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./sample_service:/app

  # user_fastapi:
  #   build:
  #     context: user_service
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 8001:8000
  #     # look up iner vs outer
  #   volumes:
  #     - ./user_service:/app
  
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_API_HOST: http://localhost:8000

            