version: "3.9"

volumes:
  jwtdown-db-data:
    external: true

  mongo-data:
    external: true

services:
  # fastapi-service:
  user:
    build:
      context: user_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./user_service:/app
    environment: # (environ)
      DATABASE_URL: mongodb://user:userpw@mongo
      DATABASE_NAME: userdb
      WAIT_HOSTS: mongo:27017
      SIGNING_KEY: 123456abcde
      # WAIT_HOSTS: mongo:27017
      # WAIT_BEFORE: 5
      # WAIT_TIMEOUT: 60

  # React:
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_FASTAPI_SERVICE: http://localhost:8000

  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: userpw

  mongo-express: # (ME)
    image: mongo-express:latest
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: userpw
      ME_CONFIG_MONGODB_URL: mongodb://user:userpw@mongo:27017/
