version: "3.9"

volumes:
  # node-mod:
  #   external: true

  fastapi:
    external: true

  mongo-data:
    external: true

services:
  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_API_HOST: http://localhost:8000

  mongo:
    image: mongo:6
    volumes:
      - ./setup/mongodb:/docker-entrypoint-initdb.d
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pw

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pw
      ME_CONFIG_MONGODB_URL: mongodb://user:pw@mongo:27017/
      # WAIT_HOSTS: mongo:27017
      # WAIT_BEFORE: 5
      # WAIT_TIMEOUT: 60

  users:
    build:
      context: users_service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./users_service:/app
    environment:
      DATABASE_URL: mongodb://user:pw@mongo
      DATABASE_NAME: users_db
      WAIT_HOSTS: mongo:27017
