version: "3.9"

volumes:
  mongo-data:
    external: true

services:
  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_API_HOST: http://localhost:8000
  # fastapi:
  #   build:
  #     context: fastapi
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./fastapi:/app
  #   environment:
  #     DATABASE_URL: postgresql://foodies:foodies@postgres/foodies
  #     MONGO_URL: mongodb://foodies:foodies@mongo
  #     MONGO_DB: foodies
  #     WAIT_HOSTS: postgres:5432,mongo:27017

  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pw

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pw
      ME_CONFIG_MONGODB_URL: mongodb://admin:pw@mongo:27017/

  users:
    build:
      context: users_service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./users_service:/app
    environment:
      DATABASE_URL: mongodb://admin:pw@mongo
      DATABASE_NAME: users_db
      WAIT_HOSTS: mongo:27017
