FROM python:3.10-bullseye
ENV PYTHONUNBUFFERED 1
RUN python -m pip install --upgrade pip
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
WORKDIR /deps 
COPY requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt
WORKDIR /app
CMD /wait && python poller.py



# COPY poller.py poller.py

# CMD /wait && echo  "HERE HERE HERE POLLER " && pwd && ls -al

