# # Build an image starting with the Python 3.7 image:
# FROM python:3.10-bullseye
# RUN python -m pip install --upgrade pip
# # Set the working directory to /deps:
# WORKDIR /deps
# # Copy requirements.txt and install the Python dependencies:
# COPY requirements.txt requirements.txt
# RUN python -m pip install -r requirements.txt
# WORKDIR /app
# CMD /wait && uvicorn main:app --reload --host 0.0.0.0

FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
WORKDIR /deps
COPY requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt
WORKDIR /app
CMD /wait && uvicorn main:app --reload --host 0.0.0.0